# Copyright 2020 The EME Authors

name: Build_Check
on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Build_Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # Install Dependencies
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # Build App
      - uses: borales/actions-yarn@v2.0.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          cmd: linux # Build on mac
